name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:
  push: {branch: ["master"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: HackerSM9
          template: classic
          config_timezone: Asia/Kolkata
          base: "header, activity, community, repositories"
          plugin_traffic: yes
          plugin_lines: yes
          plugin_introduction: yes
          plugin_gists: yes
          plugin_starlists: yes
          plugin_starlists_limit_repositories: 2
          plugin_starlists_languages: yes
          plugin_starlists_limit_languages: 15
          plugin_starlists_only: Awesome
          
      # 🧑‍🤝‍🧑 People    
      - name: Followers
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/people.followers.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_people: yes
          plugin_people_limit: 500
          plugin_people_size: 36
          plugin_people_types: followersG
