name: Generate Snake

on:
  schedule:
      # every 6 hours
    - cron: "0 * * * *"

- uses: Platane/snk@v2
  with:
    github_user_name: HackerSM9

    outputs: |
      dist/gh-snk.svg
      dist/gh-snk-d.svg?palette=github-dark
      dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
