name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: "0 0 * * *" # runs at every 12AM UTC

jobs:
  update-readme:
    permissions: write-all
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@0.7.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_TOKEN }}
          SECTION_NAME: waka
          SHOW_TIME: "True"
          SHOW_MASKED_TIME: "True"
          SHOW_TITLE: "True"
          SHOW_TOTAL: "True"
          REPOSITORY: HackerSM9/SM9-System-Detector 
